
ADD_LIBRARY(libamd STATIC IMPORTED)

ADD_LIBRARY(libcxsparse STATIC IMPORTED)

ADD_LIBRARY(libcholmod STATIC IMPORTED)

ADD_LIBRARY(libccolamd STATIC IMPORTED)

ADD_LIBRARY(libcolamd STATIC IMPORTED)

ADD_LIBRARY(libklu STATIC IMPORTED)

ADD_LIBRARY(libldl STATIC IMPORTED)

ADD_LIBRARY(libcamd STATIC IMPORTED)

ADD_LIBRARY(libbtf STATIC IMPORTED)

ADD_LIBRARY(libspqr STATIC IMPORTED)

ADD_LIBRARY(libumfpack STATIC IMPORTED)

ADD_LIBRARY(suitesparseconfig STATIC IMPORTED)